apiVersion: apps/v1
kind: Deployment
metadata:
  name: mock-service
spec:
  selector:
    matchLabels:
      app: mock-service
  template:
    metadata:
      labels:
        app: mock-service
    spec:
      containers:
      - name: mock-service
        image: hunghp666/mock-service:1.0.0
        imagePullPolicy: Always
        resources:
          requests:
            memory: "128Mi"
            cpu: "500m"
        ports:
          - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: mock-service
spec:
  selector:
    app: mock-service
  ports:
    - port: 8080
      targetPort: 8080

